name: Fornt-End-Code-Style-Checks

on: push

jobs:
  js-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: step_one
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Diff files
        id: step_two
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD ':(exclude)www/crm*')
          [ -z "$CHANGED_FILES" ] && exit 0
          echo 'CHANGED_FILES<<EOF' >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "Hello world ${{ env.CHANGED_FILES }}"

      - name: Style check
        id: step_three
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: ${{ env.CHANGED_FILES }}
#  style-check:
#    name: stylelint
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions-hub/stylelint@master
#
#  another-style-check:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: "12.x"
#      - uses: xt0rted/stylelint-problem-matcher@v1
#      - run: npm install
#      - run: npm ci
#      - run: npm test