name: Fornt-End-Code-Style-Checks

on: push

jobs:
  tests2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/