name: JSLint checks test

on: push

jobs:
  tests1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing node_modules
        run: npm install -g
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx