name: JSLint checks test

on: push

jobs:
#  tests1:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Installing node_modules
#        run: npm install -g
#      - name: Run ESLint
#        run: eslint . --ext .js,.jsx,.ts,.tsx

  variation-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: |
            CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD ':(exclude)www/crm*')
            [ -z "$CHANGED_FILES" ] && exit 0
            yarn run eslint $CHANGED_FILES

      - name: Run stylelint
        run: yarn run stylelint "**/*.css"